name: psr_database_sqlite
description: PSR Database SQLite FFI bindings
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ffi: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  test: ^1.24.0
